# Generated by Django 3.2.4 on 2021-06-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(default=None, max_length=400)),
                ('paymentId', models.CharField(default=None, max_length=400)),
                ('signature', models.CharField(default=None, max_length=400)),
            ],
        ),
    ]
