# Generated by Django 3.2.4 on 2021-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_auto_20210628_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='orderId',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paymentId',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='payments',
            name='signature',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[(1, 'success'), (2, 'failed')], max_length=50, null=True),
        ),
    ]
