# Generated by Django 3.2.4 on 2021-06-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_auto_20210628_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='payments',
            name='status',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='Payments.Publication')),
            ],
        ),
    ]
