# Generated by Django 3.2.4 on 2021-08-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0008_payments_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
