# Generated by Django 3.2.4 on 2021-08-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0010_membershipplans_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipplans',
            old_name='rate',
            new_name='amount',
        ),
    ]
