# Generated by Django 3.2.4 on 2021-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0012_payments_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
