# Generated by Django 3.2.4 on 2021-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0013_subscriptions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
