# Generated by Django 3.2.4 on 2021-11-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0016_auto_20211115_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='membership',
        ),
    ]
