# Generated by Django 3.2.4 on 2021-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0017_remove_subscriptions_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='sub_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
