# Generated by Django 3.2.4 on 2021-12-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0018_subscriptions_sub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payments.membershipplans'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payments.payments'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
