# Generated by Django 3.2.4 on 2021-12-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0019_auto_20211214_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.membershipplans'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.payments'),
        ),
    ]
