# Generated by Django 3.2.4 on 2021-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0020_auto_20211216_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplans',
            name='recurrence_count',
            field=models.IntegerField(default=1),
        ),
    ]
