# Generated by Django 3.2.4 on 2021-12-18 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0021_membershipplans_recurrence_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_membership', to='Payments.membershipplans'),
        ),
    ]
