# Generated by Django 3.2.4 on 2021-12-18 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0022_alter_subscriptions_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
