# Generated by Django 3.2.4 on 2022-01-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0023_alter_subscriptions_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='payments',
        ),
    ]
