# Generated by Django 3.2.4 on 2022-01-03 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0025_appointmentpayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentpayments',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointmentpayments',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentpayments',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
