# Generated by Django 3.2.4 on 2022-02-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalsymptoms',
            name='name',
            field=models.CharField(default='empty', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
