# Generated by Django 3.2.4 on 2022-02-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_auto_20220202_1021'),
        ('Admin', '0002_alter_criticalsymptoms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalsymptoms',
            name='complication',
            field=models.ManyToManyField(to='Analytics.Complications'),
        ),
    ]
