# Generated by Django 3.2.4 on 2022-08-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_positivecriticalsymptoms_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivecriticalsymptoms',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positive_symptoms', to='Admin.criticalsymptoms'),
        ),
    ]
