# Generated by Django 3.2.4 on 2021-12-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0002_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
