# Generated by Django 3.2.4 on 2022-05-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0004_auto_20220113_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedplan',
            name='tracker',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'diet'), (2, 'exercise')], null=True),
        ),
    ]
