# Generated by Django 3.2.4 on 2021-11-24 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0002_delete_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointmentDate', models.DateField(blank=True, null=True)),
                ('scantDate', models.DateField(blank=True, null=True)),
                ('ultraSound', models.FileField(null=True, upload_to='ultrasound')),
                ('bloodReport', models.FileField(null=True, upload_to='bloodreport')),
                ('antenatalChart', models.FileField(null=True, upload_to='antenatal')),
                ('bp', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
