# Generated by Django 3.2.4 on 2021-11-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20211124_1529'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='symptoms',
    #         name='category',
    #     ),
    #     migrations.DeleteModel(
    #         name='SymptomsCategory',
    #     ),
    # ]
