# Generated by Django 3.2.4 on 2021-11-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20211125_1115'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='SymptomsCategory',
    #         fields=[
    #             ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
    #         ],
    #     ),
    #     migrations.AddField(
    #         model_name='symptoms',
    #         name='category',
    #         field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.symptomscategory'),
    #     ),
    # ]
