# Generated by Django 3.2.4 on 2021-11-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20211125_1100'),
        ('Customer', '0006_auto_20211125_1119'),
    ]

    operations = [
    ]
