# Generated by Django 3.2.4 on 2022-01-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_alter_symptoms_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsymptoms',
            old_name='symptom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='positivecustomsymptoms',
            old_name='symptoms',
            new_name='symptom',
        ),
    ]
