# Generated by Django 3.2.4 on 2022-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_auto_20220112_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraction',
            name='painScale',
        ),
        migrations.AddField(
            model_name='contraction',
            name='pain_scale',
            field=models.CharField(blank=True, choices=[('worst pain', 'worst_pain'), ('severe', 'severe'), ('modertae', 'moderate'), ('mild', 'mild'), ('no pain', 'no_pain')], max_length=20, null=True),
        ),
    ]
