# Generated by Django 3.2.4 on 2022-01-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_contraction_pain_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraction',
            name='pain_scale',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'worst_pain'), (2, 'severe'), (3, 'moderate'), (4, 'mild'), (5, 'no_pain')], null=True),
        ),
    ]
