# Generated by Django 3.2.4 on 2022-01-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_auto_20220113_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsinput',
            name='bloodPressure',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsinput',
            name='bloodSugar',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True),
        ),
    ]
