# Generated by Django 3.2.4 on 2022-01-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_auto_20220113_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
