# Generated by Django 3.2.4 on 2022-01-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_exercises_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymainmodule',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitysubmodules',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
