# Generated by Django 3.2.4 on 2022-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_auto_20220121_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymainmodule',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
