# Generated by Django 3.2.4 on 2022-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_auto_20220202_1021'),
        ('Customer', '0021_symptoms_criticality'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='complication',
            field=models.ManyToManyField(to='Analytics.Complications'),
        ),
    ]
