# Generated by Django 3.2.4 on 2022-04-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0024_alter_symptoms_complication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercises',
            unique_together=set(),
        ),
    ]
