# Generated by Django 3.2.4 on 2022-02-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_customermedicalhistory_medicalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermedicalhistory',
            name='complication',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='complication',
            field=models.ManyToManyField(to='Analytics.Complications'),
        ),
    ]
