# Generated by Django 3.2.4 on 2022-02-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0009_rename_domestice_voilence_personaldetails_domestic_voilence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermedicalhistory',
            name='flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
