# Generated by Django 3.2.4 on 2022-05-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0011_auto_20220305_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='bmi',
            field=models.CharField(blank=True, choices=[('underweight', 'underweight'), ('normal weight', 'normal weight'), ('over weight', 'over weight')], max_length=20, null=True),
        ),
    ]
