# Generated by Django 3.2.4 on 2021-07-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0064_auto_20210728_1219'),
        ('Consultant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedplan',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.dailytrackermodule'),
        ),
    ]
