# Generated by Django 3.2.4 on 2021-07-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0002_customizedplan_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedplan',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
