# Generated by Django 3.2.4 on 2021-07-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0003_alter_customizedplan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedplan',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customizedplan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
