# Generated by Django 3.2.4 on 2021-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='Idproof',
            field=models.ImageField(null=True, upload_to='Idproof/'),
        ),
    ]
