# Generated by Django 3.2.4 on 2021-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_patientdetails_idproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='Menstruation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='Menstruation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='abortions',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='allergic_reaction',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='babies_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='diabetes',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='doctor_final_visit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='gynacology',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='hereditory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='marriedSince',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='no_of_babies_pregnant_with',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='prescription',
            field=models.ImageField(null=True, upload_to='Prescriptions/'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='surgery',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='twins',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
