# Generated by Django 3.2.4 on 2021-06-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_doctordetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='areaOfIntrerest',
        ),
    ]
