# Generated by Django 3.2.4 on 2021-06-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_doctordetails_areaofintrerest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='interests',
            field=models.CharField(default='NILL', max_length=200),
        ),
    ]
