# Generated by Django 3.2.4 on 2021-06-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_doctordetails_interests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDetails',
            new_name='CustomerDetails',
        ),
    ]
