# Generated by Django 3.2.4 on 2021-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_auto_20210619_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
