# Generated by Django 3.2.4 on 2021-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_alter_customerdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Menstruation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
