# Generated by Django 3.2.4 on 2021-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_alter_customerdetails_menstruation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='icmr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
