# Generated by Django 3.2.4 on 2021-07-03 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0026_rename_is_activee_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateJoined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
