# Generated by Django 3.2.4 on 2021-07-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_auto_20210705_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Idproof',
            field=models.FileField(null=True, upload_to='Idproof/'),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='prescription',
            field=models.FileField(null=True, upload_to='Prescriptions/'),
        ),
    ]
