# Generated by Django 3.2.4 on 2021-07-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_auto_20210706_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('passwordString', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='consultant',
            field=models.BooleanField(default=False),
        ),
    ]
