# Generated by Django 3.2.4 on 2021-07-07 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0030_auto_20210707_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
