# Generated by Django 3.2.4 on 2021-07-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0033_auto_20210707_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='Idproof',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='prescription',
        ),
    ]
