# Generated by Django 3.2.4 on 2021-07-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0035_lastupdatedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUpdateDate',
        ),
    ]
