# Generated by Django 3.2.4 on 2021-07-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0037_user_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
