# Generated by Django 3.2.4 on 2021-07-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0040_alter_customerdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
