# Generated by Django 3.2.4 on 2021-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0042_doctordetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='languages',
            field=models.CharField(default='', max_length=500),
        ),
    ]
