# Generated by Django 3.2.4 on 2021-07-12 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0044_alter_salesteamdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesteamdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesDetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
