# Generated by Django 3.2.4 on 2021-07-26 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0045_alter_salesteamdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('passwordString', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultantDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
