# Generated by Django 3.2.4 on 2021-07-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0046_consultantinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='consultant',
            field=models.ManyToManyField(to='Accounts.ConsultantInfo'),
        ),
    ]
