# Generated by Django 3.2.4 on 2021-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0049_remove_customerdetails_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='consultant',
            field=models.ManyToManyField(related_name='consultants', to='Accounts.ConsultantInfo'),
        ),
    ]
