# Generated by Django 3.2.4 on 2021-07-26 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0051_alter_customerdetails_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='consultant',
            field=models.ManyToManyField(null=True, related_name='consultants', to=settings.AUTH_USER_MODEL),
        ),
    ]
