# Generated by Django 3.2.4 on 2021-07-28 06:40

import Accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0052_alter_customerdetails_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='consultant',
            field=models.ManyToManyField(related_name='consultants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twins',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[Accounts.models.yes_or_no_Validation]),
        ),
    ]
