# Generated by Django 3.2.4 on 2021-08-07 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0053_auto_20210728_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='consultant',
            field=models.ManyToManyField(blank=True, null=True, related_name='consultants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twins',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
