# Generated by Django 3.2.4 on 2021-08-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0055_alter_customerdetails_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateJoined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
