# Generated by Django 3.2.4 on 2021-08-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0058_alter_user_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.hospitaldetails'),
        ),
    ]
