# Generated by Django 3.2.4 on 2021-08-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0059_doctordetails_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='icmr',
            new_name='referalId',
        ),
    ]
