# Generated by Django 3.2.4 on 2021-08-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0060_rename_icmr_customerdetails_referalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='icmr',
            new_name='referalId',
        ),
    ]
