# Generated by Django 3.2.4 on 2021-08-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0061_rename_icmr_doctordetails_referalid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalDetails',
            new_name='hospitalManagerDetails',
        ),
        migrations.RenameField(
            model_name='doctordetails',
            old_name='hospital',
            new_name='hospitalManager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hospital',
            new_name='hospitalManager',
        ),
    ]
