# Generated by Django 3.2.4 on 2021-08-13 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0062_auto_20210813_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmanagerdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalManagerDetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
