# Generated by Django 3.2.4 on 2021-08-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0065_alter_customerdetails_criticallity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='criticallity',
        ),
        migrations.DeleteModel(
            name='Criticality',
        ),
    ]
