# Generated by Django 3.2.4 on 2021-08-28 03:39

import Accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0066_auto_20210816_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='babies_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='diabetes',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[Accounts.validators.yes_or_no_Validation]),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='husband',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[Accounts.validators.CheckIfAlpha]),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[Accounts.validators.CheckIfAlpha]),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twins',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[Accounts.validators.yes_or_no_Validation]),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=100, null=True, validators=[Accounts.validators.CheckIfAlpha]),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[Accounts.validators.CheckIfAlpha]),
        ),
    ]
