# Generated by Django 3.2.4 on 2021-10-20 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0073_alter_customerdetails_referalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Idproof',
            field=models.FileField(blank=True, null=True, upload_to='Idproof/'),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='drugUse',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter either yes/no', regex='^(?i:yes|yess|yyess|no|noo|nnoo)$')]),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='Prescriptions/'),
        ),
    ]
