# Generated by Django 3.2.4 on 2021-10-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0074_auto_20211020_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='hospitalManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.hospitalmanagerdetails'),
        ),
    ]
