# Generated by Django 3.2.4 on 2021-11-01 04:31

import Accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0075_auto_20211020_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[Accounts.validators.CheckIfAlpha, Accounts.validators.CheckNull]),
        ),
    ]
