# Generated by Django 3.2.4 on 2021-11-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0081_customerdetails_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='ProfilePic',
            new_name='profile_img',
        ),
    ]
