# Generated by Django 3.2.4 on 2021-11-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0082_rename_profilepic_customerdetails_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_otp_verified',
            new_name='is_verified',
        ),
    ]
