# Generated by Django 3.2.4 on 2021-11-02 04:51

import Accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0084_remove_consultantinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=100, null=True, validators=[Accounts.validators.CheckIfAlpha]),
        ),
    ]
