# Generated by Django 3.2.4 on 2021-11-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0085_alter_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesteamdetails',
            name='age',
        ),
    ]
