# Generated by Django 3.2.4 on 2021-11-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0086_remove_salesteamdetails_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docDetails', to='Accounts.user'),
            preserve_default=False,
        ),
    ]
