# Generated by Django 3.2.4 on 2021-12-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0089_doctordetails_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePic/'),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePic/'),
        ),
    ]
