# Generated by Django 3.2.4 on 2021-12-13 03:30

import Accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0090_auto_20211207_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='firstname', max_length=100, validators=[Accounts.validators.CheckIfAlpha]),
        ),
    ]
