# Generated by Django 3.2.4 on 2021-12-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0093_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='/media/ProfilePic/default.jpg', null=True, upload_to='ProfilePic/'),
        ),
    ]
