# Generated by Django 3.2.4 on 2022-01-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0095_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'doctor'), (3, 'client'), (4, 'sales'), (5, 'consultant'), (6, 'hospital_manager')], null=True),
        ),
    ]
