# Generated by Django 3.2.4 on 2022-01-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0096_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='profile_img',
        ),
    ]
