# Generated by Django 3.2.4 on 2022-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0097_remove_doctordetails_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='speciality',
            field=models.CharField(choices=[('obstretician', 'obstretician'), ('paediatrician', 'paediatrician'), ('psychiatrist', 'psychiatrist'), ('deitician', 'deitician'), ('psychologist', 'psychologist')], max_length=200, null=True),
        ),
    ]
