# Generated by Django 3.2.4 on 2022-01-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0099_alter_doctordetails_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospitalManager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sales',
        ),
    ]
