# Generated by Django 3.2.4 on 2022-02-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0100_auto_20220118_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
