# Generated by Django 3.2.4 on 2022-08-24 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0101_customerdetails_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'doctor'), (3, 'client'), (4, 'sales'), (5, 'consultant'), (6, 'hospital_manager'), (7, 'dad')], null=True),
        ),
        migrations.CreateModel(
            name='DadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('wife_email', models.CharField(max_length=500)),
                ('wife_name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dad_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
