# Generated by Django 3.2.4 on 2023-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0105_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
