# Generated by Django 3.2.4 on 2023-05-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0107_firebasefcm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
