# Generated by Django 3.2.4 on 2023-07-26 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0108_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='referalId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referal_doc', to='Accounts.doctordetails'),
        ),
    ]
