# Generated by Django 3.2.4 on 2023-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0109_alter_customerdetails_referalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
