# Generated by Django 3.2.4 on 2023-07-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0111_alter_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
