# Generated by Django 3.2.4 on 2023-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0114_auto_20230731_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_tokenn',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
