# Generated by Django 3.2.4 on 2023-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0115_auto_20230731_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasefcm',
            name='fcm_token',
            field=models.TextField(),
        ),
    ]
