# Generated by Django 3.2.4 on 2023-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0119_alter_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
