# Generated by Django 3.2.4 on 2023-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0120_alter_doctordetails_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
