# Generated by Django 3.2.4 on 2023-08-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0121_alter_doctordetails_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='referalId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.doctordetails'),
        ),
    ]
