# Generated by Django 3.2.4 on 2021-07-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_alter_doctordetails_icmr'),
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('date', 'customer', 'doctor')},
        ),
    ]
