# Generated by Django 3.2.4 on 2021-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_alter_appointments_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
