# Generated by Django 3.2.4 on 2021-08-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0054_auto_20210807_1521'),
        ('Appointments', '0003_appointments_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='rescheduled',
            new_name='rescheduled_by_client',
        ),
        migrations.AddField(
            model_name='appointments',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.consultantinfo'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='rescheduled_by_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('date', 'customer', 'consultant')},
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='doctor',
        ),
    ]
