# Generated by Django 3.2.4 on 2021-10-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0075_auto_20211020_1425'),
        ('Appointments', '0007_appointments_meeting_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('date', 'customer', 'doctor', 'approved')},
        ),
    ]
