# Generated by Django 3.2.4 on 2021-11-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0009_alter_appointments_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.appointments')),
            ],
        ),
    ]
