# Generated by Django 3.2.4 on 2021-12-11 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0010_appointmentsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
