# Generated by Django 3.2.4 on 2023-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0011_appointments_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
