# Generated by Django 3.2.4 on 2023-05-27 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0012_appointments_is_rescheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
