# Generated by Django 3.2.4 on 2023-05-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0108_alter_user_options'),
        ('Appointments', '0013_auto_20230528_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to='Accounts.customerdetails'),
        ),
    ]
