# Generated by Django 3.2.4 on 2023-08-11 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0005_alter_messages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='timenow',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
