# Generated by Django 3.2.4 on 2023-08-11 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messages', '0006_messages_timenow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='timenow',
        ),
        migrations.CreateModel(
            name='CustomMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=800)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_custom_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_custom_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
