# Generated by Django 3.2.4 on 2023-08-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0007_auto_20230811_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomMessages',
        ),
    ]
