# Generated by Django 3.2.4 on 2021-07-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0033_auto_20210707_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetailsApporval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customerdetails')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.doctordetails')),
            ],
            options={
                'unique_together': {('doctor', 'customer')},
            },
        ),
    ]
