# Generated by Django 3.2.4 on 2021-07-08 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('hb_value', models.CharField(blank=True, max_length=200, null=True)),
                ('hb_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('ict_value', models.CharField(blank=True, max_length=200, null=True)),
                ('ict_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('urineRE_value', models.CharField(blank=True, max_length=200, null=True)),
                ('urineRE_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('urineCS_value', models.CharField(blank=True, max_length=200, null=True)),
                ('urineCS_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('vdrl_value', models.CharField(blank=True, max_length=200, null=True)),
                ('vdrl_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('hiv_value', models.CharField(blank=True, max_length=200, null=True)),
                ('hiv_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('rbs_first_trimester_value', models.CharField(blank=True, max_length=200, null=True)),
                ('rbs_first_trimester_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('ogct_second_trimester_value', models.CharField(blank=True, max_length=200, null=True)),
                ('ogct_second_trimester_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
