# Generated by Django 3.2.4 on 2021-07-08 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0002_investigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticallity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='investigation',
            name='creatine_normal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='creatine_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='double_marker_normal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='double_marker_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='hcv_normal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='hcv_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ogtt_second_trimester_normal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ogtt_second_trimester_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='InvestigationWithDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('tft_value', models.CharField(blank=True, max_length=200, null=True)),
                ('tft_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('tft_description', models.CharField(blank=True, max_length=200, null=True)),
                ('others_value', models.CharField(blank=True, max_length=200, null=True)),
                ('others_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('others_description', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='investigation',
            name='criticallity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.criticallity'),
        ),
    ]
