# Generated by Django 3.2.4 on 2021-07-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_custominvestigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominvestigation',
            name='investigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.investigation'),
        ),
    ]
