# Generated by Django 3.2.4 on 2021-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_investigation_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominvestigation',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='custominvestigation',
            name='normal_range',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='custominvestigation',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
