# Generated by Django 3.2.4 on 2021-08-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_auto_20210716_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetailsapporval',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='patientdetailsapporval',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
