# Generated by Django 3.2.4 on 2021-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_auto_20210805_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=200)),
            ],
        ),
    ]
