# Generated by Django 3.2.4 on 2021-08-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_customercallreposnses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criticallity',
            new_name='InvestigationCriticallity',
        ),
    ]
