# Generated by Django 3.2.4 on 2021-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_rename_criticallity_investigationcriticallity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercallreposnses',
            name='notes',
        ),
        migrations.AddField(
            model_name='customercallreposnses',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
