# Generated by Django 3.2.4 on 2021-08-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0066_auto_20210816_1222'),
        ('Sales', '0013_alter_customercallreposnses_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercallreposnses',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.salesteamdetails'),
        ),
    ]
