# Generated by Django 3.2.4 on 2021-08-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0066_auto_20210816_1222'),
        ('Sales', '0014_customercallreposnses_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvestigation',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.salesteamdetails'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.salesteamdetails'),
        ),
        migrations.AddField(
            model_name='investigationwithdescriptions',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.salesteamdetails'),
        ),
    ]
