# Generated by Django 3.2.4 on 2021-09-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_auto_20210816_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callresponses',
            options={'verbose_name': 'CallResponses (Manual)'},
        ),
        migrations.RemoveField(
            model_name='customercallreposnses',
            name='response',
        ),
    ]
