# Generated by Django 3.2.4 on 2021-09-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0018_auto_20210907_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callresponses',
            options={},
        ),
    ]
