# Generated by Django 3.2.4 on 2021-09-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0019_alter_callresponses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callresponses',
            options={'verbose_name': 'CallResponses (Manual)'},
        ),
        migrations.AddField(
            model_name='customercallreposnses',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.callresponses'),
        ),
    ]
