# Generated by Django 3.2.4 on 2021-10-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_criticalitychange'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvestigation',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
