# Generated by Django 3.2.4 on 2021-10-17 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0022_custominvestigation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_investigation', to=settings.AUTH_USER_MODEL),
        ),
    ]
