# Generated by Django 3.2.4 on 2021-10-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0023_alter_investigation_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'get_latest_by': ['lastUpdated']},
        ),
    ]
