# Generated by Django 3.2.4 on 2021-10-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0025_alter_investigation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalitychange',
            name='criticallity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.investigationcriticallity'),
        ),
    ]
