# Generated by Django 3.2.4 on 2021-10-18 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0026_criticalitychange_criticallity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalitychange',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticality_change', to=settings.AUTH_USER_MODEL),
        ),
    ]
