# Generated by Django 3.2.4 on 2021-11-03 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0086_remove_salesteamdetails_age'),
        ('Sales', '0028_criticalitychange_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='scanDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.salesteamdetails'),
            preserve_default=False,
        ),
    ]
