# Generated by Django 3.2.4 on 2021-11-03 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0029_auto_20211103_0950'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investigation',
            unique_together={('date', 'customer')},
        ),
    ]
