# Generated by Django 3.2.4 on 2023-07-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0108_alter_user_options'),
        ('Sales', '0032_investigationcriticallity_criticality'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeamCalled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customerdetails')),
            ],
        ),
    ]
