# Generated by Django 3.2.4 on 2023-07-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0033_salesteamcalled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customercallreposnses',
            unique_together=set(),
        ),
    ]
